# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-18.04'

resources:
  repositories:
  - repository: pipeline-assessment-deployment
    type: git
    name: 'Pipeline Assessment/pipeline-assessment-deployment'   
    ref: 'main'
  - repository: templates
    type: git
    name: 'Pipeline Assessment/Templates'   
    ref: 'master'

stages:
- template: azure-pipelines.yml@pipeline-assessment-deployment